services:
  wallet:
    image: wallet_test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment: 
      - FLASK_RUN_PORT= 5001
      - service_url= http://localhost:5001/
      # - service_url: https://dev.tester.issuer.eudiw.dev/
